import Head from "next/head";

import HeroSection from "../components/HeroSection";
import JobSection from "../components/JobSection";
import PartnersSection from "../components/PartnersSection";
import ConstructionSection from "../components/ConstructionSection";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Alburouj</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HeroSection />
			<JobSection />
			<PartnersSection />
			<ConstructionSection />
		</div>
	);
}
